# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caldintav_new1.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import caldintav as cdt
from os import path
#------------------------------------------------------------------------
direction = path.abspath(path.dirname(cdt.__file__))
#------------------------------------------------------------------------

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 697)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(920, 690))
        MainWindow.setMaximumSize(QtCore.QSize(920, 690))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(direction+"/icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(920, 650))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(81, 81))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(81, 81))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.project_name = QtWidgets.QLineEdit(self.centralwidget)
        self.project_name.setAlignment(QtCore.Qt.AlignCenter)
        self.project_name.setObjectName("project_name")
        self.verticalLayout.addWidget(self.project_name)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.BC_summary = QtWidgets.QLabel(self.centralwidget)
        self.BC_summary.setText("")
        self.BC_summary.setObjectName("BC_summary")
        self.gridLayout.addWidget(self.BC_summary, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.span_summary = QtWidgets.QLabel(self.centralwidget)
        self.span_summary.setText("")
        self.span_summary.setObjectName("span_summary")
        self.gridLayout.addWidget(self.span_summary, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.skew_summary = QtWidgets.QLabel(self.centralwidget)
        self.skew_summary.setMinimumSize(QtCore.QSize(140, 20))
        self.skew_summary.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.skew_summary.setText("")
        self.skew_summary.setObjectName("skew_summary")
        self.gridLayout.addWidget(self.skew_summary, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.Bstatus_summary = QtWidgets.QLabel(self.centralwidget)
        self.Bstatus_summary.setMinimumSize(QtCore.QSize(140, 20))
        self.Bstatus_summary.setText("")
        self.Bstatus_summary.setObjectName("Bstatus_summary")
        self.gridLayout.addWidget(self.Bstatus_summary, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.TotalTrainsSum = QtWidgets.QLabel(self.centralwidget)
        self.TotalTrainsSum.setMinimumSize(QtCore.QSize(130, 20))
        self.TotalTrainsSum.setText("")
        self.TotalTrainsSum.setObjectName("TotalTrainsSum")
        self.gridLayout_3.addWidget(self.TotalTrainsSum, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.Tstatus = QtWidgets.QLabel(self.centralwidget)
        self.Tstatus.setText("")
        self.Tstatus.setObjectName("Tstatus")
        self.gridLayout_3.addWidget(self.Tstatus, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        spacerItem11 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem12 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.MinSpeedSum = QtWidgets.QLabel(self.centralwidget)
        self.MinSpeedSum.setMinimumSize(QtCore.QSize(130, 20))
        self.MinSpeedSum.setText("")
        self.MinSpeedSum.setObjectName("MinSpeedSum")
        self.gridLayout_5.addWidget(self.MinSpeedSum, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 1)
        self.MaxSpeedSum = QtWidgets.QLabel(self.centralwidget)
        self.MaxSpeedSum.setMinimumSize(QtCore.QSize(130, 20))
        self.MaxSpeedSum.setText("")
        self.MaxSpeedSum.setObjectName("MaxSpeedSum")
        self.gridLayout_5.addWidget(self.MaxSpeedSum, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 2, 0, 1, 1)
        self.SpeedIncrSum = QtWidgets.QLabel(self.centralwidget)
        self.SpeedIncrSum.setMinimumSize(QtCore.QSize(130, 20))
        self.SpeedIncrSum.setText("")
        self.SpeedIncrSum.setObjectName("SpeedIncrSum")
        self.gridLayout_5.addWidget(self.SpeedIncrSum, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 3, 0, 1, 1)
        self.NumModesSum = QtWidgets.QLabel(self.centralwidget)
        self.NumModesSum.setMinimumSize(QtCore.QSize(130, 20))
        self.NumModesSum.setText("")
        self.NumModesSum.setObjectName("NumModesSum")
        self.gridLayout_5.addWidget(self.NumModesSum, 3, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 4, 0, 1, 1)
        self.TimeStepSum = QtWidgets.QLabel(self.centralwidget)
        self.TimeStepSum.setMinimumSize(QtCore.QSize(130, 20))
        self.TimeStepSum.setText("")
        self.TimeStepSum.setObjectName("TimeStepSum")
        self.gridLayout_5.addWidget(self.TimeStepSum, 4, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 5, 0, 1, 1)
        self.Astatus = QtWidgets.QLabel(self.centralwidget)
        self.Astatus.setMinimumSize(QtCore.QSize(130, 20))
        self.Astatus.setText("")
        self.Astatus.setObjectName("Astatus")
        self.gridLayout_5.addWidget(self.Astatus, 5, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_8.addWidget(self.progressBar, 2, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setMinimumSize(QtCore.QSize(130, 20))
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setMinimumSize(QtCore.QSize(70, 20))
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.submitJob = QtWidgets.QPushButton(self.centralwidget)
        self.submitJob.setObjectName("submitJob")
        self.horizontalLayout_5.addWidget(self.submitJob)
        spacerItem15 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(620, 630))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(20, 10, 100, 20))
        self.label_36.setMinimumSize(QtCore.QSize(80, 20))
        self.label_36.setObjectName("label_36")
        self.bridge_types = QtWidgets.QComboBox(self.tab)
        self.bridge_types.setGeometry(QtCore.QRect(160, 5, 125, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bridge_types.sizePolicy().hasHeightForWidth())
        self.bridge_types.setSizePolicy(sizePolicy)
        self.bridge_types.setMinimumSize(QtCore.QSize(120, 25))
        self.bridge_types.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bridge_types.setObjectName("bridge_types")
        self.bridge_types.addItem("")
        self.bridge_types.addItem("")
        self.bridge_types.addItem("")
        self.bridge_types.addItem("")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(300, 10, 150, 20))
        self.label_37.setMinimumSize(QtCore.QSize(125, 20))
        self.label_37.setObjectName("label_37")
        self.BC = QtWidgets.QComboBox(self.tab)
        self.BC.setGeometry(QtCore.QRect(470, 5, 125, 25))
        self.BC.setMinimumSize(QtCore.QSize(120, 25))
        self.BC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BC.setObjectName("BC")
        self.BC.addItem("")
        self.BC.addItem("")
        self.BC.addItem("")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(300, 40, 170, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(170, 20))
        self.label_38.setObjectName("label_38")
        self.skew_value = QtWidgets.QLineEdit(self.tab)
        self.skew_value.setGeometry(QtCore.QRect(470, 40, 120, 25))
        self.skew_value.setAlignment(QtCore.Qt.AlignCenter)
        self.skew_value.setObjectName("skew_value")
        self.label_39 = QtWidgets.QLabel(self.tab)
        self.label_39.setGeometry(QtCore.QRect(20, 40, 130, 20))
        self.label_39.setObjectName("label_39")
        self.damping_value = QtWidgets.QLineEdit(self.tab)
        self.damping_value.setGeometry(QtCore.QRect(160, 40, 120, 25))
        self.damping_value.setAlignment(QtCore.Qt.AlignCenter)
        self.damping_value.setObjectName("damping_value")
        self.label_40 = QtWidgets.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(20, 110, 200, 25))
        self.label_40.setMinimumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.BridgeProperties = QtWidgets.QTableWidget(self.tab)
        self.BridgeProperties.setGeometry(QtCore.QRect(20, 150, 541, 281))
        self.BridgeProperties.setRowCount(20)
        self.BridgeProperties.setObjectName("BridgeProperties")
        self.BridgeProperties.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.BridgeProperties.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.BridgeProperties.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.BridgeProperties.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.BridgeProperties.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.BridgeProperties.setHorizontalHeaderItem(4, item)
        self.BridgeProperties.horizontalHeader().setDefaultSectionSize(100)
        self.BridgeProperties.horizontalHeader().setMinimumSectionSize(40)
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(20, 70, 130, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(130, 25))
        self.label_41.setObjectName("label_41")
        self.number_span = QtWidgets.QSpinBox(self.tab)
        self.number_span.setGeometry(QtCore.QRect(160, 70, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_span.sizePolicy().hasHeightForWidth())
        self.number_span.setSizePolicy(sizePolicy)
        self.number_span.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.number_span.setMinimum(1)
        self.number_span.setObjectName("number_span")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 450, 211, 150))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_4.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget)
        self.label_43.setMinimumSize(QtCore.QSize(130, 20))
        self.label_43.setObjectName("label_43")
        self.verticalLayout_4.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_4.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_4.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_4.addWidget(self.label_46)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(240, 450, 316, 124))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.save_bridge = QtWidgets.QPushButton(self.layoutWidget1)
        self.save_bridge.setObjectName("save_bridge")
        self.horizontalLayout_7.addWidget(self.save_bridge)
        self.clear_bridge = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_bridge.setObjectName("clear_bridge")
        self.horizontalLayout_7.addWidget(self.clear_bridge)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.export_bridge = QtWidgets.QPushButton(self.layoutWidget1)
        self.export_bridge.setObjectName("export_bridge")
        self.verticalLayout_5.addWidget(self.export_bridge)
        self.import_bridge = QtWidgets.QPushButton(self.layoutWidget1)
        self.import_bridge.setObjectName("import_bridge")
        self.verticalLayout_5.addWidget(self.import_bridge)
        self.label_84 = QtWidgets.QLabel(self.tab)
        self.label_84.setGeometry(QtCore.QRect(240, 580, 341, 17))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_47 = QtWidgets.QLabel(self.tab_2)
        self.label_47.setGeometry(QtCore.QRect(20, 20, 130, 20))
        self.label_47.setMinimumSize(QtCore.QSize(130, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_2)
        self.label_48.setGeometry(QtCore.QRect(220, 20, 130, 20))
        self.label_48.setMinimumSize(QtCore.QSize(130, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_2)
        self.label_49.setGeometry(QtCore.QRect(450, 20, 80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.TrainTable = QtWidgets.QTableWidget(self.tab_2)
        self.TrainTable.setGeometry(QtCore.QRect(369, 50, 241, 500))
        self.TrainTable.setRowCount(60)
        self.TrainTable.setObjectName("TrainTable")
        self.TrainTable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.TrainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TrainTable.setHorizontalHeaderItem(1, item)
        self.TrainTable.horizontalHeader().setDefaultSectionSize(100)
        self.selectAll = QtWidgets.QPushButton(self.tab_2)
        self.selectAll.setGeometry(QtCore.QRect(155, 70, 60, 25))
        self.selectAll.setMinimumSize(QtCore.QSize(60, 25))
        self.selectAll.setObjectName("selectAll")
        self.selectButton = QtWidgets.QPushButton(self.tab_2)
        self.selectButton.setGeometry(QtCore.QRect(155, 100, 60, 25))
        self.selectButton.setMinimumSize(QtCore.QSize(60, 25))
        self.selectButton.setObjectName("selectButton")
        self.removeButton = QtWidgets.QPushButton(self.tab_2)
        self.removeButton.setGeometry(QtCore.QRect(155, 170, 60, 25))
        self.removeButton.setMinimumSize(QtCore.QSize(60, 25))
        self.removeButton.setObjectName("removeButton")
        self.removeAll = QtWidgets.QPushButton(self.tab_2)
        self.removeAll.setGeometry(QtCore.QRect(155, 200, 60, 25))
        self.removeAll.setMinimumSize(QtCore.QSize(60, 25))
        self.removeAll.setObjectName("removeAll")
        self.label_50 = QtWidgets.QLabel(self.tab_2)
        self.label_50.setGeometry(QtCore.QRect(20, 260, 160, 25))
        self.label_50.setMinimumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.delete_train = QtWidgets.QPushButton(self.tab_2)
        self.delete_train.setGeometry(QtCore.QRect(50, 290, 140, 27))
        self.delete_train.setMinimumSize(QtCore.QSize(140, 27))
        self.delete_train.setObjectName("delete_train")
        self.show_train = QtWidgets.QPushButton(self.tab_2)
        self.show_train.setGeometry(QtCore.QRect(210, 290, 140, 27))
        self.show_train.setMinimumSize(QtCore.QSize(140, 27))
        self.show_train.setObjectName("show_train")
        self.label_51 = QtWidgets.QLabel(self.tab_2)
        self.label_51.setGeometry(QtCore.QRect(20, 330, 250, 20))
        self.label_51.setMinimumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.save_train = QtWidgets.QPushButton(self.tab_2)
        self.save_train.setGeometry(QtCore.QRect(50, 360, 140, 27))
        self.save_train.setMinimumSize(QtCore.QSize(140, 27))
        self.save_train.setObjectName("save_train")
        self.clear_table = QtWidgets.QPushButton(self.tab_2)
        self.clear_table.setGeometry(QtCore.QRect(210, 360, 140, 27))
        self.clear_table.setMinimumSize(QtCore.QSize(140, 27))
        self.clear_table.setObjectName("clear_table")
        self.label_52 = QtWidgets.QLabel(self.tab_2)
        self.label_52.setGeometry(QtCore.QRect(20, 400, 250, 20))
        self.label_52.setMinimumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.load_train = QtWidgets.QPushButton(self.tab_2)
        self.load_train.setGeometry(QtCore.QRect(50, 430, 140, 27))
        self.load_train.setMinimumSize(QtCore.QSize(140, 27))
        self.load_train.setObjectName("load_train")
        self.label_53 = QtWidgets.QLabel(self.tab_2)
        self.label_53.setGeometry(QtCore.QRect(370, 570, 161, 20))
        self.label_53.setMinimumSize(QtCore.QSize(160, 20))
        self.label_53.setObjectName("label_53")
        self.number_axles = QtWidgets.QSpinBox(self.tab_2)
        self.number_axles.setGeometry(QtCore.QRect(550, 565, 61, 27))
        self.number_axles.setMaximum(60)
        self.number_axles.setProperty("value", 60)
        self.number_axles.setObjectName("number_axles")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(20, 550, 341, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.submit_train = QtWidgets.QPushButton(self.frame)
        self.submit_train.setGeometry(QtCore.QRect(10, 10, 160, 27))
        self.submit_train.setMinimumSize(QtCore.QSize(160, 27))
        self.submit_train.setObjectName("submit_train")
        self.delete_selected_train = QtWidgets.QPushButton(self.frame)
        self.delete_selected_train.setGeometry(QtCore.QRect(170, 10, 160, 27))
        self.delete_selected_train.setMinimumSize(QtCore.QSize(160, 27))
        self.delete_selected_train.setObjectName("delete_selected_train")
        self.label_54 = QtWidgets.QLabel(self.tab_2)
        self.label_54.setGeometry(QtCore.QRect(20, 470, 300, 20))
        self.label_54.setMinimumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.add_data = QtWidgets.QPushButton(self.tab_2)
        self.add_data.setGeometry(QtCore.QRect(50, 500, 140, 27))
        self.add_data.setMinimumSize(QtCore.QSize(140, 27))
        self.add_data.setObjectName("add_data")
        self.list_trains = QtWidgets.QListView(self.tab_2)
        self.list_trains.setGeometry(QtCore.QRect(20, 50, 130, 200))
        self.list_trains.setMinimumSize(QtCore.QSize(130, 200))
        self.list_trains.setObjectName("list_trains")
        self.list_selected = QtWidgets.QListView(self.tab_2)
        self.list_selected.setGeometry(QtCore.QRect(220, 50, 130, 200))
        self.list_selected.setMinimumSize(QtCore.QSize(130, 200))
        self.list_selected.setObjectName("list_selected")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(10, 30, 270, 100))
        self.frame_2.setMinimumSize(QtCore.QSize(270, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.interaction = QtWidgets.QRadioButton(self.frame_2)
        self.interaction.setGeometry(QtCore.QRect(30, 70, 130, 25))
        self.interaction.setMinimumSize(QtCore.QSize(130, 25))
        self.interaction.setObjectName("interaction")
        self.label_55 = QtWidgets.QLabel(self.frame_2)
        self.label_55.setGeometry(QtCore.QRect(10, 10, 180, 20))
        self.label_55.setMinimumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.movingloads = QtWidgets.QRadioButton(self.frame_2)
        self.movingloads.setGeometry(QtCore.QRect(30, 40, 130, 25))
        self.movingloads.setMinimumSize(QtCore.QSize(130, 25))
        self.movingloads.setChecked(True)
        self.movingloads.setObjectName("movingloads")
        self.DER = QtWidgets.QRadioButton(self.frame_2)
        self.DER.setGeometry(QtCore.QRect(180, 40, 80, 25))
        self.DER.setMinimumSize(QtCore.QSize(80, 25))
        self.DER.setObjectName("DER")
        self.LIR = QtWidgets.QRadioButton(self.frame_2)
        self.LIR.setGeometry(QtCore.QRect(180, 70, 80, 25))
        self.LIR.setMinimumSize(QtCore.QSize(80, 25))
        self.LIR.setObjectName("LIR")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(10, 140, 270, 100))
        self.frame_3.setMinimumSize(QtCore.QSize(270, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.timeIncr = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.timeIncr.setGeometry(QtCore.QRect(190, 60, 70, 27))
        self.timeIncr.setMinimumSize(QtCore.QSize(70, 27))
        self.timeIncr.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.timeIncr.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.timeIncr.setDecimals(3)
        self.timeIncr.setMaximum(10.0)
        self.timeIncr.setSingleStep(0.001)
        self.timeIncr.setProperty("value", 0.001)
        self.timeIncr.setObjectName("timeIncr")
        self.numberModes = QtWidgets.QSpinBox(self.frame_3)
        self.numberModes.setGeometry(QtCore.QRect(190, 30, 70, 27))
        self.numberModes.setMinimumSize(QtCore.QSize(70, 27))
        self.numberModes.setMinimum(1)
        self.numberModes.setObjectName("numberModes")
        self.label_56 = QtWidgets.QLabel(self.frame_3)
        self.label_56.setGeometry(QtCore.QRect(10, 5, 180, 20))
        self.label_56.setMinimumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.frame_3)
        self.label_57.setGeometry(QtCore.QRect(40, 35, 140, 20))
        self.label_57.setMinimumSize(QtCore.QSize(140, 20))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame_3)
        self.label_58.setGeometry(QtCore.QRect(40, 65, 141, 20))
        self.label_58.setMinimumSize(QtCore.QSize(140, 20))
        self.label_58.setObjectName("label_58")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(290, 30, 315, 211))
        self.frame_4.setMinimumSize(QtCore.QSize(315, 210))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_59 = QtWidgets.QLabel(self.frame_4)
        self.label_59.setGeometry(QtCore.QRect(10, 10, 150, 20))
        self.label_59.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.frame_4)
        self.label_60.setGeometry(QtCore.QRect(30, 50, 140, 20))
        self.label_60.setMinimumSize(QtCore.QSize(140, 20))
        self.label_60.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName("label_60")
        self.minspeed = QtWidgets.QLineEdit(self.frame_4)
        self.minspeed.setGeometry(QtCore.QRect(180, 45, 120, 27))
        self.minspeed.setMinimumSize(QtCore.QSize(120, 27))
        self.minspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.minspeed.setObjectName("minspeed")
        self.label_61 = QtWidgets.QLabel(self.frame_4)
        self.label_61.setGeometry(QtCore.QRect(30, 100, 140, 20))
        self.label_61.setMinimumSize(QtCore.QSize(140, 20))
        self.label_61.setObjectName("label_61")
        self.maxspeed = QtWidgets.QLineEdit(self.frame_4)
        self.maxspeed.setGeometry(QtCore.QRect(180, 95, 120, 27))
        self.maxspeed.setMinimumSize(QtCore.QSize(120, 27))
        self.maxspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.maxspeed.setObjectName("maxspeed")
        self.label_62 = QtWidgets.QLabel(self.frame_4)
        self.label_62.setGeometry(QtCore.QRect(30, 150, 140, 20))
        self.label_62.setMinimumSize(QtCore.QSize(140, 20))
        self.label_62.setObjectName("label_62")
        self.speedincr = QtWidgets.QLineEdit(self.frame_4)
        self.speedincr.setGeometry(QtCore.QRect(180, 145, 120, 27))
        self.speedincr.setMinimumSize(QtCore.QSize(120, 27))
        self.speedincr.setAlignment(QtCore.Qt.AlignCenter)
        self.speedincr.setObjectName("speedincr")
        self.frame_5 = QtWidgets.QFrame(self.tab_3)
        self.frame_5.setGeometry(QtCore.QRect(10, 260, 595, 171))
        self.frame_5.setMinimumSize(QtCore.QSize(595, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_63 = QtWidgets.QLabel(self.frame_5)
        self.label_63.setGeometry(QtCore.QRect(10, 10, 140, 20))
        self.label_63.setMinimumSize(QtCore.QSize(140, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.loadDist = QtWidgets.QCheckBox(self.frame_5)
        self.loadDist.setGeometry(QtCore.QRect(20, 40, 151, 22))
        self.loadDist.setObjectName("loadDist")
        self.changeMonitoredPoint = QtWidgets.QCheckBox(self.frame_5)
        self.changeMonitoredPoint.setGeometry(QtCore.QRect(20, 80, 251, 22))
        self.changeMonitoredPoint.setObjectName("changeMonitoredPoint")
        self.ParallelComp = QtWidgets.QCheckBox(self.frame_5)
        self.ParallelComp.setGeometry(QtCore.QRect(20, 120, 161, 22))
        self.ParallelComp.setObjectName("ParallelComp")
        self.label_64 = QtWidgets.QLabel(self.frame_5)
        self.label_64.setGeometry(QtCore.QRect(300, 45, 210, 17))
        self.label_64.setMinimumSize(QtCore.QSize(210, 17))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.frame_5)
        self.label_65.setGeometry(QtCore.QRect(300, 85, 210, 17))
        self.label_65.setMinimumSize(QtCore.QSize(210, 17))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.frame_5)
        self.label_66.setGeometry(QtCore.QRect(300, 125, 210, 17))
        self.label_66.setMinimumSize(QtCore.QSize(210, 17))
        self.label_66.setObjectName("label_66")
        self.sleeper_separation = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.sleeper_separation.setGeometry(QtCore.QRect(520, 40, 70, 27))
        self.sleeper_separation.setMinimumSize(QtCore.QSize(70, 27))
        self.sleeper_separation.setDecimals(2)
        self.sleeper_separation.setSingleStep(0.1)
        self.sleeper_separation.setProperty("value", 0.6)
        self.sleeper_separation.setObjectName("sleeper_separation")
        self.MPdistance = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.MPdistance.setGeometry(QtCore.QRect(520, 80, 70, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(27)
        sizePolicy.setHeightForWidth(self.MPdistance.sizePolicy().hasHeightForWidth())
        self.MPdistance.setSizePolicy(sizePolicy)
        self.MPdistance.setMinimumSize(QtCore.QSize(70, 27))
        self.MPdistance.setSingleStep(0.05)
        self.MPdistance.setObjectName("MPdistance")
        self.numberCores = QtWidgets.QSpinBox(self.frame_5)
        self.numberCores.setGeometry(QtCore.QRect(520, 120, 70, 27))
        self.numberCores.setMinimumSize(QtCore.QSize(70, 27))
        self.numberCores.setMinimum(1)
        self.numberCores.setMaximum(20)
        self.numberCores.setProperty("value", 1)
        self.numberCores.setObjectName("numberCores")
        self.AOsaveoptions = QtWidgets.QPushButton(self.tab_3)
        self.AOsaveoptions.setGeometry(QtCore.QRect(100, 480, 130, 27))
        self.AOsaveoptions.setMinimumSize(QtCore.QSize(130, 27))
        self.AOsaveoptions.setObjectName("AOsaveoptions")
        self.AOclearoptions = QtWidgets.QPushButton(self.tab_3)
        self.AOclearoptions.setGeometry(QtCore.QRect(400, 480, 130, 27))
        self.AOclearoptions.setMinimumSize(QtCore.QSize(130, 27))
        self.AOclearoptions.setObjectName("AOclearoptions")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_67 = QtWidgets.QLabel(self.tab_4)
        self.label_67.setGeometry(QtCore.QRect(10, 20, 120, 20))
        self.label_67.setMinimumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.includeTrain = QtWidgets.QPushButton(self.tab_4)
        self.includeTrain.setGeometry(QtCore.QRect(20, 190, 99, 27))
        self.includeTrain.setObjectName("includeTrain")
        self.label_68 = QtWidgets.QLabel(self.tab_4)
        self.label_68.setGeometry(QtCore.QRect(10, 230, 120, 20))
        self.label_68.setMinimumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.removeTrainsResults = QtWidgets.QPushButton(self.tab_4)
        self.removeTrainsResults.setGeometry(QtCore.QRect(20, 400, 99, 27))
        self.removeTrainsResults.setObjectName("removeTrainsResults")
        self.plotArea1 = QtWidgets.QWidget(self.tab_4)
        self.plotArea1.setGeometry(QtCore.QRect(135, 0, 480, 530))
        self.plotArea1.setMinimumSize(QtCore.QSize(480, 530))
        self.plotArea1.setObjectName("plotArea1")
        self.plotResults = QtWidgets.QPushButton(self.tab_4)
        self.plotResults.setGeometry(QtCore.QRect(10, 450, 120, 27))
        self.plotResults.setMinimumSize(QtCore.QSize(120, 27))
        self.plotResults.setObjectName("plotResults")
        self.plotAccelLimit = QtWidgets.QPushButton(self.tab_4)
        self.plotAccelLimit.setGeometry(QtCore.QRect(10, 530, 120, 27))
        self.plotAccelLimit.setMinimumSize(QtCore.QSize(120, 27))
        self.plotAccelLimit.setObjectName("plotAccelLimit")
        self.plotUIC = QtWidgets.QPushButton(self.tab_4)
        self.plotUIC.setGeometry(QtCore.QRect(10, 570, 120, 27))
        self.plotUIC.setMinimumSize(QtCore.QSize(120, 27))
        self.plotUIC.setObjectName("plotUIC")
        self.ballastTrack = QtWidgets.QRadioButton(self.tab_4)
        self.ballastTrack.setGeometry(QtCore.QRect(150, 540, 117, 22))
        self.ballastTrack.setChecked(True)
        self.ballastTrack.setObjectName("ballastTrack")
        self.slabTrack = QtWidgets.QRadioButton(self.tab_4)
        self.slabTrack.setGeometry(QtCore.QRect(150, 570, 117, 22))
        self.slabTrack.setObjectName("slabTrack")
        self.frame_6 = QtWidgets.QFrame(self.tab_4)
        self.frame_6.setGeometry(QtCore.QRect(270, 535, 340, 61))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setLineWidth(1)
        self.frame_6.setObjectName("frame_6")
        self.label_69 = QtWidgets.QLabel(self.frame_6)
        self.label_69.setGeometry(QtCore.QRect(10, 10, 90, 17))
        self.label_69.setMinimumSize(QtCore.QSize(90, 17))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.frame_6)
        self.label_70.setGeometry(QtCore.QRect(110, 10, 70, 17))
        self.label_70.setMinimumSize(QtCore.QSize(70, 17))
        self.label_70.setText("")
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.frame_6)
        self.label_71.setGeometry(QtCore.QRect(190, 10, 30, 17))
        self.label_71.setMinimumSize(QtCore.QSize(30, 17))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.frame_6)
        self.label_72.setGeometry(QtCore.QRect(10, 40, 90, 17))
        self.label_72.setMinimumSize(QtCore.QSize(90, 17))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.frame_6)
        self.label_73.setGeometry(QtCore.QRect(110, 40, 70, 17))
        self.label_73.setMinimumSize(QtCore.QSize(70, 17))
        self.label_73.setText("")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.frame_6)
        self.label_74.setGeometry(QtCore.QRect(190, 40, 30, 17))
        self.label_74.setMinimumSize(QtCore.QSize(30, 17))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.frame_6)
        self.label_75.setGeometry(QtCore.QRect(220, 10, 60, 17))
        self.label_75.setMinimumSize(QtCore.QSize(60, 17))
        self.label_75.setText("")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.frame_6)
        self.label_76.setGeometry(QtCore.QRect(290, 10, 45, 17))
        self.label_76.setMinimumSize(QtCore.QSize(45, 17))
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.frame_6)
        self.label_77.setGeometry(QtCore.QRect(220, 40, 60, 17))
        self.label_77.setMinimumSize(QtCore.QSize(60, 17))
        self.label_77.setText("")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.frame_6)
        self.label_78.setGeometry(QtCore.QRect(290, 40, 45, 17))
        self.label_78.setMinimumSize(QtCore.QSize(45, 17))
        self.label_78.setObjectName("label_78")
        self.listTrainsResults = QtWidgets.QListView(self.tab_4)
        self.listTrainsResults.setGeometry(QtCore.QRect(10, 40, 120, 140))
        self.listTrainsResults.setObjectName("listTrainsResults")
        self.plotTrains = QtWidgets.QListView(self.tab_4)
        self.plotTrains.setGeometry(QtCore.QRect(10, 250, 120, 140))
        self.plotTrains.setObjectName("plotTrains")
        self.savePlot = QtWidgets.QPushButton(self.tab_4)
        self.savePlot.setGeometry(QtCore.QRect(10, 490, 120, 27))
        self.savePlot.setObjectName("savePlot")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_79 = QtWidgets.QLabel(self.tab_5)
        self.label_79.setGeometry(QtCore.QRect(10, 10, 120, 20))
        self.label_79.setMinimumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.comboSelectedTrains = QtWidgets.QComboBox(self.tab_5)
        self.comboSelectedTrains.setGeometry(QtCore.QRect(10, 40, 120, 27))
        self.comboSelectedTrains.setMinimumSize(QtCore.QSize(120, 27))
        self.comboSelectedTrains.setObjectName("comboSelectedTrains")
        self.label_80 = QtWidgets.QLabel(self.tab_5)
        self.label_80.setGeometry(QtCore.QRect(10, 80, 120, 20))
        self.label_80.setMinimumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.comboVelo = QtWidgets.QComboBox(self.tab_5)
        self.comboVelo.setGeometry(QtCore.QRect(10, 110, 120, 27))
        self.comboVelo.setMinimumSize(QtCore.QSize(120, 27))
        self.comboVelo.setObjectName("comboVelo")
        self.plotArea2 = QtWidgets.QWidget(self.tab_5)
        self.plotArea2.setGeometry(QtCore.QRect(140, 0, 470, 580))
        self.plotArea2.setObjectName("plotArea2")
        self.plotAccelTF = QtWidgets.QPushButton(self.tab_5)
        self.plotAccelTF.setGeometry(QtCore.QRect(20, 170, 99, 27))
        self.plotAccelTF.setObjectName("plotAccelTF")
        self.plotDispTF = QtWidgets.QPushButton(self.tab_5)
        self.plotDispTF.setGeometry(QtCore.QRect(20, 220, 99, 27))
        self.plotDispTF.setObjectName("plotDispTF")
        self.clearFigure = QtWidgets.QPushButton(self.tab_5)
        self.clearFigure.setGeometry(QtCore.QRect(20, 270, 99, 27))
        self.clearFigure.setObjectName("clearFigure")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.plotArea3 = QtWidgets.QWidget(self.tab_6)
        self.plotArea3.setGeometry(QtCore.QRect(0, 0, 611, 391))
        self.plotArea3.setObjectName("plotArea3")
        self.label_81 = QtWidgets.QLabel(self.tab_6)
        self.label_81.setGeometry(QtCore.QRect(20, 410, 180, 20))
        self.label_81.setMinimumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.spinModeNumber = QtWidgets.QSpinBox(self.tab_6)
        self.spinModeNumber.setGeometry(QtCore.QRect(210, 405, 61, 27))
        self.spinModeNumber.setObjectName("spinModeNumber")
        self.label_82 = QtWidgets.QLabel(self.tab_6)
        self.label_82.setGeometry(QtCore.QRect(20, 460, 151, 20))
        self.label_82.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.FreqValue = QtWidgets.QLabel(self.tab_6)
        self.FreqValue.setGeometry(QtCore.QRect(180, 460, 91, 20))
        self.FreqValue.setMinimumSize(QtCore.QSize(90, 20))
        self.FreqValue.setText("")
        self.FreqValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FreqValue.setObjectName("FreqValue")
        self.plotVModeShape = QtWidgets.QPushButton(self.tab_6)
        self.plotVModeShape.setGeometry(QtCore.QRect(360, 405, 200, 27))
        self.plotVModeShape.setMinimumSize(QtCore.QSize(200, 27))
        self.plotVModeShape.setObjectName("plotVModeShape")
        self.plotTModeShape = QtWidgets.QPushButton(self.tab_6)
        self.plotTModeShape.setGeometry(QtCore.QRect(360, 455, 200, 27))
        self.plotTModeShape.setMinimumSize(QtCore.QSize(200, 27))
        self.plotTModeShape.setObjectName("plotTModeShape")
        self.saveModeShape = QtWidgets.QPushButton(self.tab_6)
        self.saveModeShape.setGeometry(QtCore.QRect(180, 530, 99, 27))
        self.saveModeShape.setObjectName("saveModeShape")
        self.clearModeShape = QtWidgets.QPushButton(self.tab_6)
        self.clearModeShape.setGeometry(QtCore.QRect(340, 530, 99, 27))
        self.clearModeShape.setObjectName("clearModeShape")
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_project = QtWidgets.QAction(MainWindow)
        self.new_project.setObjectName("new_project")
        self.save_project = QtWidgets.QAction(MainWindow)
        self.save_project.setObjectName("save_project")
        self.open_project = QtWidgets.QAction(MainWindow)
        self.open_project.setObjectName("open_project")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUser_Guide = QtWidgets.QAction(MainWindow)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.menuFile.addAction(self.new_project)
        self.menuFile.addAction(self.save_project)
        self.menuFile.addAction(self.open_project)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CALDINTAV 3.0"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">CALDINTAV 3.0</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Project Name "))
        self.label_5.setText(_translate("MainWindow", "Project Summary"))
        self.label_6.setText(_translate("MainWindow", "Bridge:"))
        self.label_7.setText(_translate("MainWindow", "B.C. :"))
        self.label_8.setText(_translate("MainWindow", "Spans:"))
        self.label_9.setText(_translate("MainWindow", "Skewness:"))
        self.label_10.setText(_translate("MainWindow", "Status:"))
        self.label_15.setText(_translate("MainWindow", "Trains:"))
        self.label_16.setText(_translate("MainWindow", "Total trains:"))
        self.label_18.setText(_translate("MainWindow", "Status:"))
        self.label_20.setText(_translate("MainWindow", "Anal. Opt.:"))
        self.label_21.setText(_translate("MainWindow", "Min. Speed:"))
        self.label_23.setText(_translate("MainWindow", "Max. Speed:"))
        self.label_25.setText(_translate("MainWindow", "Speed Incr.:"))
        self.label_27.setText(_translate("MainWindow", "No. Modes:"))
        self.label_29.setText(_translate("MainWindow", "Time step:"))
        self.label_31.setText(_translate("MainWindow", "Status:"))
        self.label_34.setText(_translate("MainWindow", "Process:"))
        self.label_33.setText(_translate("MainWindow", "Global"))
        self.submitJob.setText(_translate("MainWindow", "Submit &Job"))
        self.label_36.setText(_translate("MainWindow", "Bridge type:"))
        self.bridge_types.setItemText(0, _translate("MainWindow", "Select an item"))
        self.bridge_types.setItemText(1, _translate("MainWindow", "Single span"))
        self.bridge_types.setItemText(2, _translate("MainWindow", "Portal Frame"))
        self.bridge_types.setItemText(3, _translate("MainWindow", "Multi-span cont."))
        self.label_37.setText(_translate("MainWindow", "Boundary Condition:"))
        self.BC.setItemText(0, _translate("MainWindow", "Select an item"))
        self.BC.setItemText(1, _translate("MainWindow", "Simply-supported at the ends"))
        self.BC.setItemText(2, _translate("MainWindow", "Fixed at the ends"))
        self.label_38.setText(_translate("MainWindow", "Skew angle (in degrees):"))
        self.skew_value.setText(_translate("MainWindow", "Enter value"))
        self.label_39.setText(_translate("MainWindow", "Damping ratio (%):"))
        self.damping_value.setText(_translate("MainWindow", "Enter value"))
        self.label_40.setText(_translate("MainWindow", "Define bridge\'s properties:"))
        item = self.BridgeProperties.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "L (m)"))
        item = self.BridgeProperties.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "EI (N.m2)"))
        item = self.BridgeProperties.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "GJ (N.m2)"))
        item = self.BridgeProperties.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "m (kg/m)"))
        item = self.BridgeProperties.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "r (m)"))
        self.label_41.setText(_translate("MainWindow", "Number of spans:"))
        self.label_42.setText(_translate("MainWindow", "L: Span length"))
        self.label_43.setText(_translate("MainWindow", "EI: Bending stiffness"))
        self.label_44.setText(_translate("MainWindow", "GJ: Torsional stiffness"))
        self.label_45.setText(_translate("MainWindow", "m: Mass per unit length"))
        self.label_46.setText(_translate("MainWindow", "r: Radius of gyration"))
        self.save_bridge.setText(_translate("MainWindow", "&Submit bridge"))
        self.clear_bridge.setText(_translate("MainWindow", "&Clear data"))
        self.export_bridge.setText(_translate("MainWindow", "&Export bridge data to csv file"))
        self.import_bridge.setText(_translate("MainWindow", "&Import bridge from csv file"))
        self.label_84.setText(_translate("MainWindow", "Note: Maximum number of spans supported is 10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "&Bridge "))
        self.label_47.setText(_translate("MainWindow", "Available trains"))
        self.label_48.setText(_translate("MainWindow", "Selected trains"))
        self.label_49.setText(_translate("MainWindow", "Train data"))
        item = self.TrainTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Axle Dist. (m)"))
        item = self.TrainTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Axle Load (N)"))
        self.selectAll.setText(_translate("MainWindow", ">>"))
        self.selectButton.setText(_translate("MainWindow", ">"))
        self.removeButton.setText(_translate("MainWindow", "<"))
        self.removeAll.setText(_translate("MainWindow", "<<"))
        self.label_50.setText(_translate("MainWindow", "From Available trains"))
        self.delete_train.setText(_translate("MainWindow", "&Delete train"))
        self.show_train.setText(_translate("MainWindow", "&Show train data"))
        self.label_51.setText(_translate("MainWindow", "Create new train from train data"))
        self.save_train.setText(_translate("MainWindow", "Sa&ve train"))
        self.clear_table.setText(_translate("MainWindow", "&Clear table"))
        self.label_52.setText(_translate("MainWindow", "Create new train from file"))
        self.load_train.setText(_translate("MainWindow", "&Load train\'s file"))
        self.label_53.setText(_translate("MainWindow", "Number of train axles:"))
        self.submit_train.setText(_translate("MainWindow", "S&ubmit selected trains"))
        self.delete_selected_train.setText(_translate("MainWindow", "Delete selected tra&ins"))
        self.label_54.setText(_translate("MainWindow", "Create new train for interaction analysis"))
        self.add_data.setText(_translate("MainWindow", "Add data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "&Train data"))
        self.interaction.setText(_translate("MainWindow", "&Interaction"))
        self.label_55.setText(_translate("MainWindow", "Dynamic analysis type"))
        self.movingloads.setText(_translate("MainWindow", "M&oving Loads"))
        self.DER.setText(_translate("MainWindow", "DER"))
        self.LIR.setText(_translate("MainWindow", "RIL"))
        self.label_56.setText(_translate("MainWindow", "Modal analysis options"))
        self.label_57.setText(_translate("MainWindow", "Number of modes:"))
        self.label_58.setText(_translate("MainWindow", "Time increment (s):"))
        self.label_59.setText(_translate("MainWindow", "Train speed options"))
        self.label_60.setText(_translate("MainWindow", "Min. speed (km/h)"))
        self.minspeed.setText(_translate("MainWindow", "Enter value"))
        self.label_61.setText(_translate("MainWindow", "Max. speed (km/h)"))
        self.maxspeed.setText(_translate("MainWindow", "Enter value"))
        self.label_62.setText(_translate("MainWindow", "Speed incr. (km/h)"))
        self.speedincr.setText(_translate("MainWindow", "Enter value"))
        self.label_63.setText(_translate("MainWindow", "Advanced options"))
        self.loadDist.setText(_translate("MainWindow", "&Load distribution"))
        self.changeMonitoredPoint.setText(_translate("MainWindow", "&Change default monitored point"))
        self.ParallelComp.setText(_translate("MainWindow", "&Parallel computing"))
        self.label_64.setText(_translate("MainWindow", "Sleeper separation (m):"))
        self.label_65.setText(_translate("MainWindow", "Monitored point distance (m): "))
        self.label_66.setText(_translate("MainWindow", "Number of cores:"))
        self.AOsaveoptions.setText(_translate("MainWindow", "&Submit options"))
        self.AOclearoptions.setText(_translate("MainWindow", "Clear &options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "&Analysis Options"))
        self.label_67.setText(_translate("MainWindow", "Selected trains"))
        self.includeTrain.setText(_translate("MainWindow", "&Include train"))
        self.label_68.setText(_translate("MainWindow", "Plotted trains"))
        self.removeTrainsResults.setText(_translate("MainWindow", "&Remove train"))
        self.plotResults.setText(_translate("MainWindow", "&Plot results"))
        self.plotAccelLimit.setText(_translate("MainWindow", "Ma&x. Accel. Limit"))
        self.plotUIC.setText(_translate("MainWindow", "&UIC DAF"))
        self.ballastTrack.setText(_translate("MainWindow", "Ballast track"))
        self.slabTrack.setText(_translate("MainWindow", "Slab track"))
        self.label_69.setText(_translate("MainWindow", "Max. Accel.:"))
        self.label_71.setText(_translate("MainWindow", "at"))
        self.label_72.setText(_translate("MainWindow", "Max. DAF:"))
        self.label_74.setText(_translate("MainWindow", "at"))
        self.label_76.setText(_translate("MainWindow", "km/h"))
        self.label_78.setText(_translate("MainWindow", "km/h"))
        self.savePlot.setText(_translate("MainWindow", "Save Figure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "&Global results"))
        self.label_79.setText(_translate("MainWindow", "Select train"))
        self.label_80.setText(_translate("MainWindow", "Select speed"))
        self.plotAccelTF.setText(_translate("MainWindow", "Plot Accel."))
        self.plotDispTF.setText(_translate("MainWindow", "Plot Disp. "))
        self.clearFigure.setText(_translate("MainWindow", "&Clear figure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "&History results"))
        self.label_81.setText(_translate("MainWindow", "Vibration mode number:"))
        self.label_82.setText(_translate("MainWindow", "Frequency (Hz):"))
        self.plotVModeShape.setText(_translate("MainWindow", "Plot vertical mode shape"))
        self.plotTModeShape.setText(_translate("MainWindow", "Plot torsional mode shape"))
        self.saveModeShape.setText(_translate("MainWindow", "&Save figure"))
        self.clearModeShape.setText(_translate("MainWindow", "&Clear figure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "&Modes Vibra."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.new_project.setText(_translate("MainWindow", "New Project"))
        self.new_project.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.save_project.setText(_translate("MainWindow", "Save Project"))
        self.save_project.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.open_project.setText(_translate("MainWindow", "Load Project"))
        self.open_project.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionUser_Guide.setText(_translate("MainWindow", "User\'s Guide"))
        self.actionUser_Guide.setShortcut(_translate("MainWindow", "Ctrl+U"))

